Repository dan-chez/car_manager_ui, pull requests merged in 2024-09, with the labels that each got.

#17 Feature: Update GitHub actions
  .github/workflows/car_manager_ui.yml
Labels: enhancement

#16 [CARMAN-224] Add more usage examples to RichText showcase
  example/lib/showcases/rich_text_showcase.dart
Labels: enhancement

#18 [CARMAN-229] Move Empty List To Package
  example/assets/animations/cmloading.json
  example/assets/images/svg/car.svg
  example/assets/images/svg/cm_car_error.svg
  example/assets/images/svg/success.svg
  example/lib/components_showcases.dart
  example/lib/constants/image_constants.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/dialogs_showcase.dart
  example/lib/showcases/empty_list_showcase.dart
  example/pubspec.yaml
  lib/carmanager_ui.dart
  lib/src/components/cm_empty_list.dart
  test/src/components/cm_empty_list_test.dart
Labels: enhancement

#14 [CARMAN-230] Create Readme
  README.md
Labels: enhancement

#20 [CARMAN-234] Add CMBriefCard To UI Package
  example/assets/images/svg/folder.svg
  example/assets/images/svg/loupe.svg
  example/lib/components_showcases.dart
  example/lib/constants/image_constants.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/brief_card_showcase.dart
  example/lib/showcases/showcase_app_base.dart
  lib/carmanager_ui.dart
  lib/src/components/cm_brief_card.dart
  lib/src/constants/app_colors_constants.dart
  lib/src/constants/button_constants.dart
  lib/src/constants/cm_icons.dart
  test/src/components/cm_brief_card_test.dart
Labels: enhancement

#21 [CARMAN-233] CMTextCard moved to UI package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcase_utils.dart
  example/lib/showcases/report_tile_showcase.dart
  example/pubspec.lock
  lib/assets/fonts/CMIcons.ttf
  lib/carmanager_ui.dart
  lib/src/components/report_tile/report_tile.dart
  lib/src/constants/app_colors_constants.dart
  lib/src/constants/button_constants.dart
  lib/src/constants/cm_icons.dart
  lib/src/utils/extensions/number_extensions.dart
  lib/src/utils/extensions/string_extensions.dart
  pubspec.yaml
  test/src/components/report_tile/report_tile_test.dart
  test/src/utils/extensions/number_extensions_test.dart
  test/src/utils/extensions/string_extensions_test.dart
Labels: enhancement

#27 [SUPPORT] Fix code coverage branch in README
  README.md
Labels: documentation

#26 [CARMAN-238] Move Summary Card To UI Package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/summary_card_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/cm_summary_card.dart
  lib/src/constants/app_colors_constants.dart
  test/src/components/cm_summary_card_test.dart
Labels: enhancement

#25 [CARMAN-237] Move Info Card To UI Package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/info_card_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/cm_empty_list.dart
  lib/src/components/cm_info_card.dart
  lib/src/constants/app_colors_constants.dart
  lib/src/constants/cm_icons.dart
  test/src/components/cm_info_card_test.dart
Labels: enhancement

#28 [CARMAN-236] HorizontalInfoCard widget moved to UI package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/horizontal_info_card_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/horizontal_info_card.dart
  lib/src/constants/app_colors_constants.dart
  test/src/components/horizontal_info_card_test.dart
Labels: enhancement

#24 [CARMAN-240] Move Vertical Info Card To Package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/vertical_info_card_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/vertical_info_card.dart
  test/src/components/vertical_info_card_test.dart
Labels: enhancement

#23 [CARMAN-235] Move Expense Summary Card To Package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/expense_summary_card_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/expense_summary_card.dart
  lib/src/constants/app_colors_constants.dart
  test/src/components/expense_summary_card_test.dart
  test/src/components/report_tile/report_tile_test.dart
Labels: enhancement

#30 [SUPPORT* Bumb packages versions
  example/pubspec.lock
  pubspec.yaml
Labels: documentation, enhancement

#31 Support: Fix minor release errors
  CHANGELOG.md
  README.md
Labels: documentation

#22 [CARMAN-239] Move Toggle Button To Package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/toggle_button_showcase.dart
  example/pubspec.lock
  lib/carmanager_ui.dart
  lib/src/components/cm_toggle_button.dart
  lib/src/constants/app_colors_constants.dart
  pubspec.yaml
  test/src/components/cm_toggle_button_test.dart
  test/src/components/report_tile/report_tile_test.dart
Labels: enhancement

#34 Support: Release 0.0.1+1
  CHANGELOG.md
  example/pubspec.lock
Labels: release

#35 Support: Update pull_request_template.md with checklist
  .github/pull_request_template.md
Labels: documentation

#36 Support: Run dart format . in project
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/brief_card_showcase.dart
  example/lib/showcases/button_showcase.dart
  example/lib/showcases/cm_appbar/cm_appbar_back_showcase.dart
  example/lib/showcases/cm_appbar/cm_appbar_no_back_showcase.dart
  example/lib/showcases/dialogs_showcase.dart
  example/lib/showcases/dropdown_showcase.dart
  example/lib/showcases/empty_list_showcase.dart
  example/lib/showcases/expense_summary_card_showcase.dart
  example/lib/showcases/horizontal_info_card_showcase.dart
  example/lib/showcases/page_title_showcase.dart
  example/lib/showcases/report_tile_showcase.dart
  example/lib/showcases/rich_text_showcase.dart
  example/lib/showcases/text_field_showcase.dart
  example/lib/showcases/toggle_button_showcase.dart
  example/lib/showcases/vertical_info_card_showcase.dart
  lib/src/components/cm_appbar.dart
  lib/src/components/cm_brief_card.dart
  lib/src/components/cm_info_card.dart
  lib/src/components/cm_rich_text.dart
  lib/src/components/cm_toggle_button.dart
  lib/src/components/dialogs/error/error_dialog.dart
  lib/src/components/dropdown/cm_dropdown.dart
  lib/src/components/horizontal_info_card.dart
  lib/src/components/report_tile/report_tile.dart
  lib/src/components/text_field/cm_text_field.dart
  lib/src/components/text_field/money_text_field/money_text_editing_controller.dart
  lib/src/components/vertical_info_card.dart
  lib/src/constants/cm_icons.dart
  lib/src/constants/decoration_constants.dart
  lib/src/constants/text_constants.dart
  lib/src/utils/cm_scroll_behavior.dart
  test/src/components/buttons/cm_icon_button_test.dart
  test/src/components/buttons/primary_button_test.dart
  test/src/components/cm_appbar_test.dart
  test/src/components/cm_brief_card_test.dart
  test/src/components/cm_empty_list_test.dart
  test/src/components/cm_info_card_test.dart
  test/src/components/cm_summary_card_test.dart
  test/src/components/cm_toggle_button_test.dart
  test/src/components/dialogs/confirm_dialog_test.dart
  test/src/components/dialogs/error_dialog_test.dart
  test/src/components/dialogs/loading_dialog_test.dart
  test/src/components/dropdown/cm_dropdown_test.dart
  test/src/components/expense_summary_card_test.dart
  test/src/components/horizontal_info_card_test.dart
  test/src/components/page_title/page_title_test.dart
  test/src/components/report_tile/report_tile_test.dart
  test/src/components/text_field/cm_money_text_field_test.dart
  test/src/components/text_field/cm_multiline_text_field_test.dart
  test/src/components/text_field/cm_text_field_test.dart
  test/src/components/vertical_info_card_test.dart
Labels: documentation
