Repository dan-chez/car_manager_ui, pull requests merged in 2025-02, with the labels that each got.

#48 Support: Export CloseIconButton
  lib/carmanager_ui.dart
Labels: enhancement

#49 [CARMAN-283] Fix CMPageTitle Alignment
  example/lib/showcases/page_title_showcase.dart
  example/pubspec.lock
  lib/src/components/cm_page_title.dart
Labels: bug

#50 [CARMAN-287] CMDateButton moved to package
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/date_button_showcase.dart
  lib/carmanager_ui.dart
  lib/src/components/buttons/cm_date_button.dart
  lib/src/constants/cm_icons.dart
  test/src/components/buttons/cm_date_button_test.dart
Labels: enhancement

#51 [Support] Bump package version 0.0.2
  CHANGELOG.md
  pubspec.yaml
Labels: release

#52 Support: Release 0.0.2
  CHANGELOG.md
  pubspec.yaml
Labels: release

#53 Support: Release 0.0.2
  CHANGELOG.md
  example/lib/components_showcases.dart
  example/lib/navigation/go_router_provider.dart
  example/lib/showcases/date_button_showcase.dart
  example/lib/showcases/page_title_showcase.dart
  example/pubspec.lock
  lib/carmanager_ui.dart
  lib/src/components/buttons/cm_date_button.dart
  lib/src/components/buttons/primary_button.dart
  lib/src/components/cm_brief_card.dart
  lib/src/components/cm_empty_list.dart
  lib/src/components/cm_info_card.dart
  lib/src/components/cm_page_title.dart
  lib/src/components/cm_rich_text.dart
  lib/src/components/cm_summary_card.dart
  lib/src/components/cm_toggle_button.dart
  lib/src/components/dialogs/confirm/confirm_dialog.dart
  lib/src/components/dialogs/error/error_dialog.dart
  lib/src/components/dropdown/cm_dropdown.dart
  lib/src/components/expense_summary_card.dart
  lib/src/components/horizontal_info_card.dart
  lib/src/components/report_tile/report_tile.dart
  lib/src/components/text_field/cm_multiline_text_field.dart
  lib/src/components/vertical_info_card.dart
  lib/src/constants/cm_icons.dart
  lib/src/constants/decoration_constants.dart
  lib/src/constants/text_style_constants.dart
  pubspec.yaml
  test/src/components/buttons/cm_date_button_test.dart
Labels: release
